# Generated by Django 4.0.1 on 2022-01-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfoutlet',
            name='ip_address',
            field=models.CharField(default='127.0.0.1', max_length=15),
        ),
    ]
