# Generated by Django 4.0.1 on 2022-01-18 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_rfoutlet_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='RF433Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ip_address', models.CharField(default='127.0.0.1', max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='rfoutlet',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='rfoutlet',
            name='rf_433_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.rf433module'),
        ),
    ]
