# Generated by Django 4.0.1 on 2022-01-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_rf433module_remove_rfoutlet_ip_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RGBLight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('unique_id', models.IntegerField()),
                ('on_off_state', models.BooleanField(default=False)),
                ('red', models.IntegerField(default=0)),
                ('green', models.IntegerField(default=0)),
                ('blue', models.IntegerField(default=0)),
            ],
        ),
    ]
