# Generated by Django 4.0.1 on 2022-02-04 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_alter_rgblight_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RF433Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('on_payload', models.IntegerField(default=1)),
                ('is_on', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='rf433module',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='rf433module',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rf433module',
            name='unique_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='rf433module',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.DeleteModel(
            name='RFOutlet',
        ),
        migrations.AddField(
            model_name='rf433outlet',
            name='rf_433_mqtt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.rf433module'),
        ),
    ]
