# Generated by Django 4.0.1 on 2022-02-04 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_rf433outlet_remove_rf433module_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rf433module',
            name='unique_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='rf433outlet',
            name='on_payload',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='rf433outlet',
            name='rf_433_mqtt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.rf433module'),
        ),
    ]
